"""Phase 1 Layer 1 quality reports (ASE v2.1 §B7)."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from athena_research.ase.event_backtest import EVENTS_PATH

MIN_CANDIDATES = 500
MIN_MEAN_NET_R = -0.15


def phase1_report(events_path: Path | None = None, out_path: Path | None = None) -> Path:
    src = events_path or EVENTS_PATH
    report_path = out_path or Path("reports") / "phase1_layer1_report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)

    if not src.exists():
        body = _empty_report("awaiting full PTIS history run — no events parquet")
        report_path.write_text(body, encoding="utf-8")
        return report_path

    df = pd.read_parquet(src)
    lines = ["# ASE Phase 1 — Layer 1 event report", ""]

    gate_rows: list[str] = []
    if df.empty:
        lines.append("No candidates recorded.")
        gate_rows.append("| (none) | 0 | n/a | **FAIL** |")
    else:
        grouped = df.groupby(["family", "horizon"], sort=True)
        for (family, horizon), g in grouped:
            n = len(g)
            mean_r = float(g["net_R"].mean())
            status = "PASS" if n >= MIN_CANDIDATES and mean_r >= MIN_MEAN_NET_R else "FAIL"
            gate_rows.append(f"| {family} / {horizon} | {n} | {mean_r:.4f} | **{status}** |")

            lines.extend(
                [
                    f"## {family} / {horizon}",
                    "",
                    f"- candidates: {n}",
                    f"- mean net_R: {mean_r:.4f}",
                    f"- median net_R: {float(g['net_R'].median()):.4f}",
                    f"- win rate: {float((g['net_R'] > 0).mean()):.2%}",
                    "",
                    "### Exit reason mix",
                    "",
                ]
            )
            for reason, cnt in g["exit_reason"].value_counts().items():
                lines.append(f"- {reason}: {cnt}")
            lines.append("")

            lines.append("### Top / bottom instruments (mean net_R)")
            lines.append("")
            by_inst = g.groupby("instrument")["net_R"].mean().sort_values()
            for sym in list(by_inst.head(5).index) + list(by_inst.tail(5).index):
                lines.append(f"- {sym}: {by_inst[sym]:.4f}")
            lines.extend(["", "---", ""])

    header = [
        "## Exit gate",
        "",
        f"PASS if candidates ≥ {MIN_CANDIDATES} per family-horizon AND mean net_R ≥ {MIN_MEAN_NET_R}R.",
        "",
        "| family / horizon | candidates | mean net_R | gate |",
        "|------------------|------------|------------|------|",
        *gate_rows,
        "",
    ]
    report_path.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    return report_path


def _empty_report(reason: str) -> str:
    return "\n".join(
        [
            "# ASE Phase 1 — Layer 1 event report",
            "",
            f"**Status:** {reason}",
            "",
            "## Exit gate",
            "",
            "| family / horizon | candidates | mean net_R | gate |",
            "|------------------|------------|------------|------|",
            "| (pending) | 0 | n/a | **FAIL** |",
            "",
        ]
    )


def phase2_validation_report(
    *,
    out_path: Path | None = None,
    fold_results: dict | None = None,
) -> Path:
    """Generate Phase 2 validation report stub (holdout untouched)."""
    report_path = out_path or Path("reports") / "phase2_validation_report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    fold_results = fold_results or {}
    lines = [
        "# ASE Phase 2 — Validation report (stub)",
        "",
        "Holdout split remains untouched until `ase_cli holdout-eval`.",
        "",
        "## Walk-forward summary",
        "",
        "| family / horizon | folds | provisional | holdout |",
        "|------------------|-------|-------------|---------|",
    ]
    if not fold_results:
        lines.append("| (pending) | 0 | n/a | **UNTOUCHED** |")
    else:
        for key, row in sorted(fold_results.items()):
            lines.append(
                f"| {key} | {row.get('folds', 0)} | {row.get('provisional', 'n/a')} | **UNTOUCHED** |"
            )
    lines.extend(["", "## Notes", "", "- Generated by `ase_cli validate`", ""])
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return report_path
