import yaml

# Load config.yaml keys
with open('config.yaml', encoding='utf-8') as f:
    cfg = yaml.safe_load(f)
se = cfg.get('SCALP_ENGINE', {})
yaml_keys = set(se.keys())

read_keys = {
    "AAA_ABSORPTION_RECENT_BARS", "AAA_ACCUMULATION_LOOKBACK", "AAA_ENABLED",
    "ABSORPTION_RECENT_BARS", "ABSORPTION_SMA_PERIOD", "ABSORPTION_VOL_MULT",
    "ABS_MAX_MOVE_ATR", "ABS_SMA_PERIOD", "ABS_VOL_MULT", "AI_GRADING",
    "ALLOW_NEUTRAL_CVD_AT_VA_EXTREME", "ALLOW_TIMELESS_SCALP_CANDLES",
    "ATR_PERIOD", "ATR_SL_ENABLED", "BALANCE_THRESHOLD", "BIAS_REQUIRE_CONFIRMATION",
    "BIAS_TIMEFRAME", "BINANCE_WEIGHT", "BLOCK_STOCK_VP_ON_EODHD_1H_VOLUME",
    "BT_ENABLED", "BT_GRADE_SESSION_LIVE_PARITY", "BT_MAX_CONCURRENT",
    "BT_SCRATCH_BARS", "BT_SCRATCH_ENABLED", "BT_SCRATCH_MIN_R", "BT_SLIPPAGE_TICKS",
    "BT_VP_LOOKBACK_BARS", "BT_WALK_BARS", "BUFFER_USE_ATR", "BYBIT_WEIGHT",
    "CANDLE_FRESHNESS_ENABLED", "CONSECUTIVE_LOSS_HALVE", "CRYPTO_MIN_BUFFER_PIPS",
    "CVD_PROXY_HARD_VETO", "CVD_SMOOTH_PERIOD", "ENABLED",
    "ENGINE_B_CRYPTO_LEVELS_FEED", "ENGINE_B_CRYPTO_LEVELS_SIGNAL_FEED_FALLBACK",
    "ENGINE_D_FEE_GUARD_ENABLED", "ENGINE_D_MAX_COST_R", "ENGINE_D_MIN_STOP_PCT",
    "ENGINE_D_MOVE_SL_TO_BE_AFTER_TP1", "ENGINE_D_PARTIAL_EXIT_ENABLED",
    "ENGINE_D_RUNNER_ENABLED", "ENGINE_D_SAME_CANDLE_POLICY", "ENGINE_D_TP1_SIZE",
    "EODHD_LIVE_V2_MAX_QUOTE_LAG_SEC", "EODHD_STOCK_EXCHANGE_SUFFIX_MAP",
    "EODHD_VOLUME_OVERLAY_BACKTEST_ENABLED", "EODHD_VOLUME_OVERLAY_LIVE_ENABLED",
    "EODHD_VOLUME_WARMER_ENABLED", "EODHD_VOLUME_WARMER_ENGINE_A_ENABLED",
    "EODHD_VOLUME_WARMER_INTERVAL_SEC", "EODHD_VOLUME_WARMER_SLOW_INTERVAL_SEC",
    "EODHD_VOLUME_WARMER_TIMEFRAMES", "EQUITY_MIN_BUFFER_PIPS",
    "ESTIMATED_FEE_PCT", "ESTIMATED_FEE_PCT_BY_ASSET", "ESTIMATED_SLIPPAGE_PCT",
    "ESTIMATED_SLIPPAGE_PCT_BY_ASSET", "EXECUTION_HYDRATE_CANDLE_QUALITY",
    "EXECUTION_MIN_GRADE", "EXECUTION_TIMEFRAME", "FOREX_BUFFER_PCT",
    "GRADE_A_SIZE_MULT", "GRADE_B_SIZE_MULT", "GRADE_C_SIZE_MULT",
    "GRADE_D_SIZE_MULT", "GRADE_PERSIST_COMPONENTS", "GRADE_SESSIONS",
    "GRADE_SESSIONS_BY_ASSET", "GRADE_SIZING_ENABLED", "GRADE_STRONG_ABSORPTION_MIN_COUNT",
    "GRADE_THRESHOLDS", "H1_CANDLES", "LIVEV2_POLL_INTERVAL_SEC",
    "LIVE_MILESTONE_MANAGEMENT", "LONDON_OPEN_SKIP_MINUTES", "M15_CANDLES",
    "M1_CANDLES", "M5_CANDLES", "MARKET_CANDLE_MAX_AGE_SEC",
    "MARKET_OPEN_CHECK_ENABLED", "MARKET_TICK_MAX_AGE_SEC", "MAX_DAILY_LOSSES",
    "MAX_SPREAD_PIPS", "MAX_SPREAD_POINTS", "MAX_SPREAD_POINTS_OVERRIDES",
    "MIN_GRADE", "MIN_GRADE_AUTO_EXECUTE", "MIN_RR", "MT5_ABSORPTION_MIN_COUNT",
    "NY_OPEN_SKIP_MINUTES", "PREMARKET_DELTA_PROXY_MIN_CANDLES",
    "PREMARKET_DELTA_PROXY_TOP_LEVELS", "REQUIRE_AGGTRADE_FOR_CRYPTO_STRICT",
    "REQUIRE_REAL_VOLUME_FOR_COMMODITY", "REQUIRE_REAL_VOLUME_FOR_FOREX",
    "REQUIRE_REAL_VOLUME_FOR_INDEX", "REQUIRE_REAL_VOLUME_FOR_STOCKS",
    "SCALP_PAIRS", "SCALP_SCAN_UNIVERSE", "SCALP_VP_LOOKBACK_BARS",
    "SESSION_FILTER", "SESSION_MODE", "SETUP_MEAN_REVERSION", "SETUP_TREND",
    "SIGNAL_EXECUTABLE_FALSE_WHEN_FRESHNESS_BLOCKS", "SIZE_CUT_AFTER_2R",
    "SKIP_CRYPTO_ON_AGGTRADE_UNAVAILABLE", "SL_AFTER_PARTIAL",
    "STOP_RUN_DETECTION_ENABLED", "STOP_RUN_WICK_PCT", "STOP_RUN_WICK_SUSPECT_PCT",
    "STRICT_FABIO_GATE_ENABLED", "STRICT_TREND_LOCATION_LVN_ONLY",
    "TIME_OF_DAY_ADJUSTMENT_ENABLED", "TP1_R_MULT", "TP2_ENABLED",
    "TRADE_BUCKET_CVD_ENABLED", "TRADE_BUCKET_MAX_AGE_SEC", "TRADE_BUCKET_MIN_LEVELS",
    "TRADE_BUCKET_MIN_VOLUME", "TRADE_BUCKET_VP_ENABLED", "TREND_CONT_SL_FALLBACK_PCT",
    "USE_FORMING_FOR_BIAS", "USE_FORMING_FOR_STRUCTURE", "USE_FORMING_FOR_TRIGGER",
    "VOLUME_DIVERGENCE_ENABLED", "VOLUME_DIVERGENCE_MODERATE_PCT",
    "VOLUME_DIVERGENCE_STRONG_PCT", "VP_BINS", "VP_ENABLED",
    "VP_INVALIDATE_RANGE_PROXY_FOR_STOCKS", "VP_LOOKBACK_BARS", "VP_LVN_FACTOR",
    "VP_PROXIMITY_PCT", "VP_PROXIMITY_USE_ATR", "VP_SESSION_AWARE", "VP_VA_PCT",
    "VWAP_BAND_MULT", "VWAP_ENABLED", "WITH_TREND_ONLY",
}

print("=== READ IN CODE but not in YAML (aliases/legacy/nested) ===")
for k in sorted(read_keys - yaml_keys):
    print(f"  {k}")

print("\n=== IN YAML but NOT READ IN CODE (dead candidates) ===")
for k in sorted(yaml_keys - read_keys):
    print(f"  {k}")

print(f"\n=== SUMMARY ===")
print(f"YAML keys: {len(yaml_keys)}")
print(f"Read keys: {len(read_keys)}")
print(f"Dead candidates: {len(yaml_keys - read_keys)}")
