"""
Crypto Signal Funnel Audit
Diagnoses why crypto signals are not being generated by Engines A, B, and C.
Uses the /api/pair-scan endpoint to get real diagnostic data.
"""

import sys
import json
import logging
import requests
from datetime import datetime
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from config import CONFIG
import importlib.util

# Load athena.py as a module directly (not the package)
spec = importlib.util.spec_from_file_location("athena_module", "athena.py")
athena_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(athena_module)

# Get CRYPTO_PAIRS from the loaded module
CRYPTO_PAIRS = athena_module.CRYPTO_PAIRS

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
log = logging.getLogger("crypto_audit")

# Get enabled crypto pairs
ENABLED_CRYPTO = [p for p in CRYPTO_PAIRS if p.get("enabled", True)]

API_BASE = "http://localhost:5000"

def run_crypto_funnel_audit():
    """Run complete crypto signal funnel audit using /api/scan-naked endpoint."""
    log.info(f"Starting Crypto Signal Funnel Audit for {len(ENABLED_CRYPTO)} enabled pairs")
    
    report = {
        "audit_timestamp": datetime.utcnow().isoformat(),
        "total_pairs": len(ENABLED_CRYPTO),
        "pairs": {}
    }
    
    # Call /api/scan-naked once for all crypto pairs with debug mode
    log.info("Calling /api/scan-naked with debug mode for all crypto pairs...")
    try:
        response = requests.post(
            f"{API_BASE}/api/scan-naked",
            json={
                "assetClass": "crypto",
                "style": "auto",
                "debug": True
            },
            timeout=120
        )
        
        if response.status_code != 200:
            log.error(f"API returned {response.status_code}")
            return report
        
        data = response.json()
        debug_rows = data.get("debugRows", [])
        log.info(f"Received {len(debug_rows)} debug rows from API")
        
    except requests.exceptions.RequestException as e:
        log.error(f"API request failed: {e}")
        return report
    
    # Process each enabled crypto pair
    for pair in ENABLED_CRYPTO:
        pair_display = pair["display"]
        log.info(f"Auditing {pair_display}...")
        
        pair_report = {
            "symbol": pair["symbol"],
            "display": pair_display,
            "source": pair["source"],
            "engine_a": {},
            "engine_b": {},
            "engine_c": {},
            "candle_freshness": {},
            "final_reason": "Unknown"
        }
        
        # Find this pair's debug row
        debug_row = None
        for row in debug_rows:
            if row.get("pair") == pair_display:
                debug_row = row
                break
        
        if not debug_row:
            pair_report["final_reason"] = "No debug row found in response"
            report["pairs"][pair_display] = pair_report
            log.warning(f"{pair_display}: No debug row found")
            continue
        
        # Extract candle counts
        pair_report["candle_freshness"] = {
            "d1_count": debug_row.get("d1_count", 0),
            "h4_count": debug_row.get("zone_count", 0),
            "h1_count": debug_row.get("entry_count", 0),
            "atr_count": debug_row.get("atr_count", 0),
            "atr_value": debug_row.get("atr_value"),
            "zone_tf": debug_row.get("zone_tf"),
            "entry_tf": debug_row.get("entry_tf"),
            "atr_tf": debug_row.get("atr_tf")
        }
        
        # Extract Engine B data from debug row
        pair_report["engine_b"] = {
            "best_long": {
                "score": debug_row.get("long_confidence_score", 0),
                "pass": debug_row.get("long_passed", False),
                "fail_gates": debug_row.get("failed_gate_names", []),
                "structural_verdict": debug_row.get("long_structural_verdict")
            },
            "best_short": {
                "score": debug_row.get("short_confidence_score", 0),
                "pass": debug_row.get("short_passed", False),
                "fail_gates": debug_row.get("failed_gate_names", []),
                "structural_verdict": debug_row.get("short_structural_verdict")
            },
            "style_profile": debug_row.get("style"),
            "timeframe": debug_row.get("entry_tf")
        }
        
        # Set final reason from debug row
        pair_report["final_reason"] = debug_row.get("final_reject_reason", "Unknown")
        
        # Engine A and C are not covered by /api/scan-naked, mark as not applicable
        pair_report["engine_a"] = {
            "score": 0,
            "threshold": 2.4,
            "direction": None,
            "pass": False,
            "fail_reasons": ["Engine A not covered by /api/scan-naked"]
        }
        
        pair_report["engine_c"] = {
            "decision_state": None,
            "consensus_type": None,
            "final_signal": False,
            "reason": "Engine C not covered by /api/scan-naked"
        }
        
        report["pairs"][pair_display] = pair_report
    
    # Save report
    report_path = Path(__file__).parent / "logs" / "crypto_funnel_audit.json"
    report_path.parent.mkdir(exist_ok=True)
    
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2)
    
    log.info(f"Audit complete. Report saved to {report_path}")
    
    # Print summary
    print("\n" + "="*80)
    print("CRYPTO SIGNAL FUNNEL AUDIT SUMMARY")
    print("="*80)
    
    engine_a_pass = sum(1 for p in report["pairs"].values() if p["engine_a"].get("pass", False))
    engine_b_pass = sum(1 for p in report["pairs"].values() 
                       if p.get("engine_b", {}).get("best_long", {}).get("pass", False) or p.get("engine_b", {}).get("best_short", {}).get("pass", False))
    engine_c_pass = sum(1 for p in report["pairs"].values() if p["engine_c"].get("final_signal", False))
    
    print(f"Total pairs audited: {report['total_pairs']}")
    print(f"Engine A passed: {engine_a_pass}/{report['total_pairs']}")
    print(f"Engine B passed: {engine_b_pass}/{report['total_pairs']}")
    print(f"Engine C signals: {engine_c_pass}/{report['total_pairs']}")
    print("\nPer-pair breakdown:")
    
    for display, p in report["pairs"].items():
        a_score = p["engine_a"].get("score", 0)
        a_thresh = p["engine_a"].get("threshold", 0)
        b_long_score = p["engine_b"].get("best_long", {}).get("score", 0)
        b_short_score = p["engine_b"].get("best_short", {}).get("score", 0)
        c_signal = p["engine_c"].get("final_signal", False)
        
        print(f"  {display:15s} | A: {a_score:.2f}/{a_thresh:.2f} | B-L: {b_long_score:.2f} | B-S: {b_short_score:.2f} | C: {'✓' if c_signal else '✗'}")
        if not c_signal and p["final_reason"]:
            print(f"                 Reason: {p['final_reason'][:100]}")
    
    print("="*80)
    
    return report

if __name__ == "__main__":
    run_crypto_funnel_audit()
