from __future__ import annotations

PLATFORM_VERSION = "2.0.0-candidate.1"
SIMULATOR_VERSION = "athena-simulator-v2.1"
CATALOG_SCHEMA_VERSION = 1

ENGINES = ("A", "B")
ENGINE_STYLES = {
    "A": ("auto", "intraday", "swing"),
    "B": ("auto", "scalp", "intraday", "swing"),
}

CERTIFICATION_STATES = ("CERTIFIED", "PARTIAL_CERTIFIED", "EXPLORATORY")
RUN_STATUSES = (
    "QUEUED",
    "PREPARING_DATA",
    "RUNNING",
    "VALIDATING",
    "COMPLETED",
    "FAILED",
    "CANCELLED",
    "INTERRUPTED",
)
TERMINAL_RUN_STATUSES = frozenset({"COMPLETED", "FAILED", "CANCELLED"})

TIMEFRAME_SECONDS = {
    "M1": 60,
    "M5": 5 * 60,
    "M15": 15 * 60,
    "M30": 30 * 60,
    "H1": 60 * 60,
    "H4": 4 * 60 * 60,
    "D1": 24 * 60 * 60,
}

DEFAULT_LOOKBACK_DAYS = 365 * 3
DEFAULT_INITIAL_CAPITAL = 100_000.0
DEFAULT_RISK_PER_TRADE = 0.01
DEFAULT_MAX_CONCURRENT_POSITIONS = 10
DEFAULT_RANDOM_SEED = 17_071_986
DEFAULT_HOLDOUT_FRACTION = 0.20
DEFAULT_WALK_FORWARD_FOLDS = 5
DEFAULT_TRAIN_FRACTION = 0.40
DEFAULT_OOS_FRACTION = 0.08
DEFAULT_MAX_HOLD_BARS = 240

LEGACY_RETIREMENT_CODE = "LEGACY_BACKTEST_RETIRED"
FX_RETIREMENT_CODE = "FX_BACKTEST_ATTESTATION_RETIRED"

