"""Engine D naked-chart scalp trade playbook."""

from __future__ import annotations

from ai_playbooks.contracts import PLAYBOOK_SCHEMA_VERSION


def get_engine_d_scalp_playbook() -> dict:
    return {
        "schemaVersion": PLAYBOOK_SCHEMA_VERSION,
        "engine": "D",
        "name": "Engine D Naked Chart Scalp Review",
        "reviewOrder": "Market State -> Location -> Aggression -> Entry Model -> Invalidation -> Decision",
        "principles": [
            "M5 is the default context chart; M1 is execution zoom only, not primary context.",
            "Do not chase stretched candles or extended displacement.",
            "Do not long directly into supply or HVN resistance.",
            "Do not short directly into demand or HVN support.",
            "Do not trade when market state, location, and aggression do not align.",
            "Use WATCH_ONLY when state is unclear. Use NO_TRADE only for hard invalidation or a concrete no-trade reason.",
            "If location is poor, output WAIT, not ENTRY_NOW.",
            "If aggression contradicts direction, output WAIT unless it creates hard invalidation.",
            "If RR is poor after waiting for confirmation, output NO_TRADE with a concrete noTradeReason.",
            "AI review is advisory only and never grants execution permission.",
        ],
        "marketStates": [
            "trending",
            "balancing",
            "expanding",
            "compressing",
            "choppy",
            "no_trade",
            "transition",
        ],
        "locationChecklist": [
            "value area / POC / VAH / VAL if available",
            "HVN / LVN if available",
            "supply / demand zones",
            "session high / low",
            "prior swing high / low",
            "liquidity pools",
            "premium / discount if available",
            "whether price is in a poor location to chase",
        ],
        "aggressionChecklist": [
            "aggressive buying / selling",
            "absorption",
            "exhaustion",
            "delta / volume imbalance if available",
            "candle displacement",
            "wick rejection",
            "failed breakout / sweep and reclaim",
            "whether aggression confirms or contradicts the trade",
        ],
        "entryModels": [
            "LVN_REJECTION_CONTINUATION",
            "PULLBACK_TO_VALUE_REJECTION",
            "SWEEP_AND_RECLAIM",
            "BREAK_RETEST_HOLD",
            "FAILED_BREAKOUT_REVERSAL",
            "ABSORPTION_REVERSAL",
            "MOMENTUM_CONTINUATION_AFTER_PULLBACK",
            "NO_TRADE",
        ],
        "invalidations": [
            "Identify exact invalidation level or zone.",
            "State what would prove the setup wrong.",
            "Verify stop is structurally valid for current structure.",
            "Verify RR is acceptable for the scalp context.",
            "Flag if SL is too tight or too wide for current structure.",
        ],
        "decisions": [
            "ENTRY_NOW",
            "WAIT_FOR_PULLBACK",
            "WAIT_FOR_ACCEPTANCE",
            "WATCH_ONLY",
            "NO_TRADE",
            "INVALIDATED",
        ],
        "mustRejectIf": [
            "Market state, location, and aggression do not align.",
            "Market state is unclear or choppy.",
            "Location is poor for chasing entry.",
            "Aggression contradicts proposed direction.",
            "Long into supply/HVN resistance or short into demand/HVN support.",
            "M1-only context without M5 alignment.",
            "RR poor after required confirmation.",
            "Invalidation level missing for ENTRY_NOW.",
        ],
        "requiredOutputFields": [
            "tradeSkillVersion",
            "reviewType",
            "decision",
            "direction",
            "confidence",
            "marketState",
            "locationAssessment",
            "aggressionAssessment",
            "entryModel",
            "invalidationLevel",
            "invalidationReason",
            "entryAllowedNow",
            "waitReason",
            "noTradeReason",
            "requiredConfirmation",
            "chartReadSummary",
        ],
    }
