"""Engine D naked-chart scalp trade playbook."""

from __future__ import annotations

from ai_playbooks.contracts import PLAYBOOK_SCHEMA_VERSION


def get_engine_d_scalp_playbook() -> dict:
    return {
        "schemaVersion": PLAYBOOK_SCHEMA_VERSION,
        "engine": "D",
        "name": "Engine D Fabio/Carmine Scalp Review",
        "reviewOrder": (
            "Session Context -> Market State -> Effort vs Result -> Location -> "
            "Trapped Traders -> Entry Model -> Target -> Invalidation -> Management -> Decision"
        ),
        "principles": [
            "Use server-trusted sessionContext.currentSession — do NOT infer session from screenshot alone.",
            "M5 is the default context chart; M1 is execution zoom only, not primary context.",
            "Apply Model A (NY trend squeeze) or Model B (London/low-vol mean reversion) per sessionContext.preferredModel.",
            "Classify effort-vs-result BEFORE choosing entry model; map to aggressionClassification.",
            "Do not chase first breakout candle; wait for LVN/reclaim/micro-pullback (Model A).",
            "For mean-reversion / failed-breakout: POC is primary target magnet; reject middle-of-value entries.",
            "Do not chase stretched candles or extended displacement.",
            "Do not long directly into supply or HVN resistance.",
            "Do not short directly into demand or HVN support.",
            "Stop must be structural (behind sweep/absorption/LVN failure) — reject ATR-only generic stops.",
            "Respect casino/time degradation: downgrade midday compression; hard-reject late session marginal setups.",
            "Fabio/Carmine scalps should move green quickly; scratch/BE if trade stalls after trigger.",
            "Use WATCH_ONLY when state is unclear. Use NO_TRADE only for hard invalidation or concrete noTradeReason.",
            "If location is poor, output WAIT, not ENTRY_NOW.",
            "If aggression contradicts direction, output WAIT unless it creates hard invalidation.",
            "If RR is poor after waiting for confirmation, output NO_TRADE with a concrete noTradeReason.",
            "AI review is advisory only and never grants execution permission.",
        ],
        "marketStates": [
            "trending",
            "balancing",
            "expanding",
            "compressing",
            "choppy",
            "no_trade",
            "transition",
        ],
        "locationChecklist": [
            "value area / POC / VAH / VAL if available",
            "HVN / LVN if available",
            "supply / demand zones",
            "session high / low",
            "prior swing high / low",
            "liquidity pools",
            "premium / discount if available",
            "whether price is in a poor location to chase",
        ],
        "aggressionChecklist": [
            "aggressive buying / selling",
            "absorption",
            "exhaustion",
            "delta / volume imbalance if available",
            "candle displacement",
            "wick rejection",
            "failed breakout / sweep and reclaim",
            "whether aggression confirms or contradicts the trade",
        ],
        "sessionModelSwitch": {
            "useServerSessionContext": True,
            "modelA": {
                "name": "NY_TREND_SQUEEZE",
                "preferWhen": [
                    "sessionContext.currentSession in NY_OPEN, NY_PREMARKET",
                    "sessionContext.volatilityRegime expanding (NORMAL/HIGH/EXTREME)",
                    "price broke from balance / imbalance market state",
                    "pullback into LVN or reclaim level visible",
                    "trapped counter-trend traders likely",
                    "initiative aggression resumes after absorption",
                ],
                "requiredLogic": [
                    "Do NOT chase first breakout candle.",
                    "Wait for LVN/reclaim/micro-pullback confirmation.",
                    "Confirm high effort + strong result OR trapped-side absorption followed by reclaim.",
                    "Target structural liquidity or next profile level.",
                    "Stop behind LVN/reclaim failure (structural, not ATR-generic).",
                ],
            },
            "modelB": {
                "name": "LONDON_MEAN_REVERSION",
                "preferWhen": [
                    "sessionContext.currentSession in LONDON or NY_MIDDAY compression",
                    "lower volatility (LOW/NORMAL regime)",
                    "range/balance conditions",
                    "price sweeps VAH/VAL, prior high/low, premarket/session extreme",
                    "breakout fails with absorption/exhaustion",
                    "price reclaims range",
                ],
                "requiredLogic": [
                    "Target POC as primary magnet.",
                    "Reject trades in middle of value unless already in management.",
                    "Stop behind sweep wick / absorption wall.",
                    "Do NOT enter if price already travelled too far from reclaim.",
                ],
            },
            "lowVolFailedBreakout": {
                "name": "LOW_VOL_FAILED_BREAKOUT",
                "preferWhen": [
                    "sessionContext.volatilityRegime LOW",
                    "balance market state",
                    "failed breakout at VAH/VAL/session extreme",
                ],
            },
        },
        "effortVsResultDecisionTable": [
            {
                "classification": "HIGH_EFFORT_NO_RESULT",
                "meaning": "ABSORPTION",
                "action": "fade/reversal only at qualified macro level (VAH/VAL/session extreme)",
                "aggressionClassification": "ABSORPTION",
            },
            {
                "classification": "HIGH_EFFORT_HIGH_RESULT",
                "meaning": "INITIATIVE_AGGRESSION",
                "action": "continuation only after pullback/retest — do NOT chase",
                "aggressionClassification": "INITIATIVE_AGGRESSION",
            },
            {
                "classification": "LOW_EFFORT_STALLED_RESULT",
                "meaning": "EXHAUSTION",
                "action": "mean-reversion candidate if at VAH/VAL/liquidity extreme",
                "aggressionClassification": "EXHAUSTION",
            },
            {
                "classification": "LOW_EFFORT_HIGH_RESULT",
                "meaning": "thin/liquidity vacuum",
                "action": "caution; require reclaim/acceptance before entry",
                "aggressionClassification": "NO_CLEAR_FLOW",
            },
        ],
        "trappedTraderRules": {
            "fields": ["trappedSide", "trapTrigger", "squeezeFuelScore", "explanation"],
            "trappedSideValues": ["LONGS", "SHORTS", "NONE", "UNKNOWN"],
            "trapTriggerValues": [
                "FAILED_BREAKDOWN",
                "FAILED_BREAKOUT",
                "SWEEP_AND_RECLAIM",
                "LVN_REJECTION",
                "NONE",
            ],
            "rules": [
                "Failed breakdown below support/VAL/session low + reclaim = trapped SHORTS.",
                "Failed breakout above resistance/VAH/session high + reclaim lower = trapped LONGS.",
                "Highest conviction when aggressive side absorbed first, then price reclaims broken level.",
                "If no trapped side exists, continuation/reversal conviction must be lower.",
                "squeezeFuelScore 0-100: higher when absorption + reclaim + session alignment.",
            ],
        },
        "pocTargetMagnetRules": [
            "For mean-reversion / failed-breakout / balance setups: POC is primary structural target.",
            "Prefer POC over arbitrary RR target if POC is reachable and path is clean.",
            "If POC too close to justify risk, downgrade or reject setup.",
            "If price already at/near POC, reject new mean-reversion entry.",
            "Reject middle-of-value entries unless managing an existing position.",
        ],
        "casinoTimeDegradationRules": [
            "NY_OPEN first clean delivery window: allow Model A/B if all rules align.",
            "Midday compression (NY_MIDDAY / COMPRESSION_WINDOW): downgrade most setups unless extremely clean absorption/reclaim at major level.",
            "Late session (NY_AFTERNOON, NY_CLOSE, LATE_SESSION_RISK): reject marginal setups; require clear liquidity event and clean invalidation.",
            "After daily target/profit lock (profitLockActive): recommend stop trading / review only.",
            "OVERNIGHT_AVOID: WATCH_ONLY or NO_TRADE unless exceptional structural event.",
        ],
        "structuralStopGeometry": {
            "rejectIf": [
                "SL is only ATR-derived and not tied to structural invalidation.",
                "SL too wide relative to the model.",
                "SL too tight but placed inside noise rather than behind true failure point.",
                "TP1/target does not compensate for structural stop width.",
            ],
            "byEntryModel": {
                "SWEEP_AND_RECLAIM": "valid SL = behind swept wick / failed auction extreme / absorption wall",
                "ABSORPTION_REVERSAL": "valid SL = behind absorption wall / aggressive failed extreme",
                "LVN_REJECTION_CONTINUATION": "valid SL = behind LVN/retest failure",
                "FAILED_BREAKOUT_REVERSAL": "valid SL = behind failed breakout extreme",
            },
            "stopProblemValues": [
                "NONE",
                "TOO_WIDE_ATR_GENERIC",
                "TOO_TIGHT_INSIDE_NOISE",
                "WRONG_SIDE_OF_LEVEL",
                "NO_STRUCTURAL_INVALIDATION",
            ],
            "expectedBehaviorValues": [
                "IMMEDIATE_GREEN_OR_BAIL",
                "ALLOW_RETEST",
                "WAIT_FOR_ACCEPTANCE",
            ],
        },
        "tradeManagementRules": {
            "forEntryNow": True,
            "rules": [
                "Fabio/Carmine scalps should move green quickly.",
                "If trade stalls after trigger, recommend scratch/BE rather than hope.",
                "Structural outlier: partial scale at first target, runner to liquidity.",
                "Marginal setup only: recommend WATCH_ONLY or WAIT.",
            ],
            "moveToBETriggerValues": [
                "TP1_HIT",
                "INITIAL_MOMENTUM_PULSE",
                "STRUCTURE_RECLAIM_HOLD",
                "NONE",
            ],
        },
        "entryModels": [
            "LVN_REJECTION_CONTINUATION",
            "PULLBACK_TO_VALUE_REJECTION",
            "SWEEP_AND_RECLAIM",
            "BREAK_RETEST_HOLD",
            "FAILED_BREAKOUT_REVERSAL",
            "ABSORPTION_REVERSAL",
            "MOMENTUM_CONTINUATION_AFTER_PULLBACK",
            "NO_TRADE",
        ],
        "invalidations": [
            "Identify exact structural invalidation level or zone (not ATR-only).",
            "State what would prove the setup wrong.",
            "Verify stop is structurally valid for current entry model.",
            "Verify RR is acceptable for scalp context and structural stop width.",
            "Flag if SL is too tight or too wide for current structure.",
            "Populate invalidationAssessment with stopPlacementValid and stopProblem.",
        ],
        "sessionRegimeSwitch": [
            "Identify current session (Asia / London / NY) and whether a session open or regime switch is in progress.",
            "Treat the first 15-30 minutes after a major session open as transition — downgrade entry timing unless structure is clean.",
            "When regime switches from balancing to trending (or vice versa), require fresh acceptance before ENTRY_NOW.",
            "Do not assume the prior session's POC or value area still governs after a regime switch without displacement confirmation.",
        ],
        "effortVsResult": [
            "Compare volume/delta effort to price result: high effort with little progress suggests absorption or trap risk.",
            "Effort without result at a key level favors WAIT or WATCH_ONLY, not ENTRY_NOW.",
            "Effort aligned with displacement through a level supports continuation entries after pullback.",
        ],
        "trappedTraderLogic": [
            "Look for stop-runs, failed breakouts, and quick reclaim that trap late entrants on the wrong side.",
            "When trapped-trader behavior is visible (sweep + reclaim + opposing delta), favor reversal models or WAIT.",
            "Do not ENTRY_NOW into obvious trap zones without acceptance confirmation.",
        ],
        "pocMagnet": [
            "Treat POC as a magnet in balancing regimes — expect mean reversion toward POC unless displacement expands value.",
            "Avoid chasing away from POC when price is extended; prefer pullback entries toward POC/VAL/VAH.",
            "When price sits at POC, require aggression confirmation before directional ENTRY_NOW.",
        ],
        "casinoTimeDegradation": [
            "Degrade entry quality during low-liquidity windows (late Asia, pre-London, last hour before NY close) unless structure is exceptional.",
            "Reduce tradeabilityScore when session time favors random chop ('casino time') without clear location edge.",
            "Prefer WATCH_ONLY or WAIT when time-of-day and market state both suggest degraded follow-through.",
        ],
        "structuralStopPrinciples": [
            "Stop must sit beyond the structural invalidation (swing, LVN edge, sweep wick), not inside noise.",
            "Flag micro-stops inside the current candle range or inside fee-guard minimum distance.",
            "Compare stop distance to recent ATR: too tight = noise stop; too wide = poor scalp RR.",
            "For longs, SL below demand/sweep low; for shorts, SL above supply/sweep high — never arbitrary mid-range.",
        ],
        "decisions": [
            "ENTRY_NOW",
            "WAIT_FOR_PULLBACK",
            "WAIT_FOR_ACCEPTANCE",
            "WATCH_ONLY",
            "NO_TRADE",
            "INVALIDATED",
        ],
        "mustRejectIf": [
            "Ignoring server sessionContext in favor of screenshot session guess.",
            "Market state, location, and aggression do not align.",
            "Market state is unclear or choppy.",
            "Location is poor for chasing entry (middle-of-value without Model B).",
            "Aggression contradicts proposed direction.",
            "Long into supply/HVN resistance or short into demand/HVN support.",
            "M1-only context without M5 alignment.",
            "RR poor after required confirmation.",
            "Invalidation level missing for ENTRY_NOW.",
            "Stop is ATR-generic without structural tie for entry model.",
            "Midday/late session marginal setup without clean liquidity event.",
            "Mean-reversion entry at/near POC.",
            "No trapped side when squeeze continuation claimed.",
        ],
        "requiredOutputFields": [
            "tradeSkillVersion",
            "reviewType",
            "decision",
            "direction",
            "confidence",
            "marketState",
            "locationAssessment",
            "aggressionAssessment",
            "aggressionClassification",
            "effortVsResultClassification",
            "entryModel",
            "invalidationLevel",
            "invalidationReason",
            "invalidationAssessment",
            "trappedTraderAssessment",
            "targetLogic",
            "sessionQuality",
            "sessionConvictionAdjustment",
            "managementPlan",
            "entryAllowedNow",
            "waitReason",
            "noTradeReason",
            "requiredConfirmation",
            "chartReadSummary",
        ],
        "extendedOutputFields": [
            "aggressionClassification",
            "effortVsResultClassification",
            "trappedTraderAssessment",
            "targetLogic",
            "sessionQuality",
            "sessionConvictionAdjustment",
            "invalidationAssessment",
            "managementPlan",
        ],
    }
