"""Engine A confluence/context trade playbook."""

from __future__ import annotations

from ai_playbooks.contracts import PLAYBOOK_SCHEMA_VERSION


def get_engine_a_playbook() -> dict:
    return {
        "schemaVersion": PLAYBOOK_SCHEMA_VERSION,
        "engine": "A",
        "name": "Engine A Confluence Context Review",
        "reviewOrder": "Confluence -> Factor Alignment -> Direction Quality -> Entry Timing -> Decision",
        "principles": [
            "Review confluence and factor alignment before approving entry.",
            "Ground every judgment in the supplied engineAContext.diagnostics and V3 factorScores, not a freehand chart read; see indicatorUsage.",
            "Live Engine A is Engine A V3: four components trend/momentum/location/volume. Do not require legacy directionalScore/activeDirectionalFactors unless supplied.",
            "High Engine A score does not imply entry is acceptable now.",
            "Distinguish direction valid from entry timing poor.",
            "Acceptable timing is a valid and common outcome: a confirmed BOS with acceptance/retest, a pullback to structure, or a breakout retest are tradeable continuation entries, not chasing.",
            "Downgrade timing only on concrete evidence — use the setup/location timeframe for price-to-value distance, the trigger timeframe for momentum, and atrDiagnostics.atr_tf for volatility units; for crypto also use vwapExtended/vwapDistanceAtr. Do not downgrade as a reflex because the score passed.",
            "Score high but location/timing poor requires WAIT, not ENTRY_NOW; a signal can be directionally valid while execution waits.",
            "No trade when evidence is weak, conflicted, or missing required context.",
            "Use factorDiagnostics.scoringTimeframes and the server-supplied policy role fields as the actual scoring contract. Trend uses regime/bias/structure roles, momentum uses trigger, and location/volume use setup; never substitute a static D1/H4/H1 or H1/H4 matrix.",
        ],
        "timeframeContract": {
            "roleMapping": {
                "trend": "factorDiagnostics.scoringTimeframes.trend and regimeTf/biasTf/structureTf",
                "momentum": "factorDiagnostics.scoringTimeframes.momentum and triggerTf",
                "location": "factorDiagnostics.scoringTimeframes.location and setupTf",
                "volume": "factorDiagnostics.scoringTimeframes.volume and setupTf",
                "atr": "atrDiagnostics.atr_tf",
            },
            "authoritativeFields": [
                "factorDiagnostics.scoringTimeframes",
                "engineAContext.entryTimeframe",
                "engineAContext.entryUsesActiveCandle",
                "engineAContext.activeEntryGate",
                "regimeTf",
                "biasTf",
                "structureTf",
                "setupTf",
                "triggerTf",
                "atrDiagnostics.atr_tf",
            ],
            "resolved_profile": "timeframeProfile — the resolved policy profile name stamped on the signal.",
            "profile_source": "policySource — SYMBOL_OVERRIDE / SCORE_GROUP_OVERRIDE / ASSET_STYLE_DEFAULT / SAFE_FALLBACK / CONFIG_CONFLICT.",
            "symbol_override_applied": "symbolOverrideApplied — true when a symbol-level override patched roles on top of the group/asset template.",
            "score_group": "timeframePolicyDiagnostics.scoreGroup — the score group the policy resolved under.",
            "engine_overlay": "engineId + style — the engine/style overlay applied after profile resolution.",
            "execution_mode": "executionMode — live_quote production execution; executionTf is advisory execution context only.",
            "m5_policy": "m5Policy — disabled|conditional. Conditional M5 requires server-stamped m5Eligible=true with m5EligibilityReasons; M5 refines timing only, never direction or conviction.",
        },
        "entryModels": [
            "CONFLUENCE_CONTINUATION",
            "PULLBACK_TO_STRUCTURE",
            "BREAKOUT_RETEST",
            "MEAN_REVERSION_AT_VALUE",
            "NO_TRADE",
        ],
        "indicatorUsage": {
            "factorScores.trend / factorDiagnostics.components.trend": "V3 trend component strength in the proposed direction; weak/negative trend contradicts a continuation thesis. Legacy alias: diagnostics.trendScore.",
            "factorScores.momentum / factorDiagnostics.components.momentum": "V3 momentum component. RSI extreme against direction or momentum divergence is a timing warning, not an automatic reject. Legacy alias: diagnostics.momentumScore.",
            "factorScores.ortho.location / factorDiagnostics.components.location": "V3 location/value component scored on entryTimeframe. components.location.contribution is its deterministic score contribution; poor location with high confluence still warrants WAIT. Legacy flat alias: diagnostics.locationScore.",
            "factorScores.ortho.volume / factorDiagnostics.components.volume": "V3 volume/flow component scored on entryTimeframe. components.volume.contribution is its deterministic score contribution. When volumeType is tick (forex) or mixed (commodity) do NOT penalize on volume. Legacy flat alias: diagnostics.volumeScore.",
            "factorDiagnostics.components": "Authoritative per-component signal, quality, weight, contribution, and availability. Cite these values; never recompute or mutate deterministic contributions.",
            "entryTimeframe / entryUsesActiveCandle / activeEntryGate": "Actual entry-scoring timeframe and live-bucket proof. For configured lower-TF entries, activeEntryGate.passed=false is a hard timing blocker; never substitute H1 evidence.",
            "factorDiagnostics.minDirectionalFailed / confluenceScore / confluenceThreshold": "V3 gate diagnostics. If minDirectionalFailed is true, direction quality failed — do not treat as a high-quality entry.",
            "setupId / decision / qualified": "V3 setup identity and TRADE/WATCH/NO_SIGNAL decision — advisory context; never mutate deterministic scores.",
            "legacyScore / legacyDirection vs policyScore": "legacyScore/legacyDirection are the pre-policy shadow evaluation kept for rollback diagnostics and UI display; policyScore is the authoritative score under the enforced timeframe policy. When they disagree, judge the signal on policyScore and treat legacy* as shadow context only.",
            "diagnostics.adxD1 / adxH4": "Trend strength / regime. Low ADX = ranging; do not treat range chop as a continuation entry, and prefer mean-reversion logic at value.",
            "diagnostics.rsi": "Momentum confirmation alongside factorScores.momentum.",
            "diagnostics.ema50 / ema200 / dema200 with factorDiagnostics.scoringTimeframes": "Engine A EMA evidence. Confirm direction against the policy trend roles, and gauge entry extension only with setup-timeframe value/EMA evidence in the ATR units identified by atrDiagnostics.atr_tf. An H4 reference alone cannot verify M30 location or M15 momentum.",
            "diagnostics.emaTrendPeriod / emaMomentumPeriod / emaLongPeriod / rsiPeriod / rsiTimeframe": "Per-group periods Engine A actually scored with (e.g. forex 26/60, crypto 18/40, rsi 18 vs 12). The chart draws its EMA/RSI lines at these same per-group periods on confirmed bars — the legacy ema50/rsi14 key names are aliases, not literal 50/14 periods. indicatorParity compares chart vs Engine A values only when the chart is on H4; any entry in indicatorParity.mismatches means the values genuinely diverge and is a real warning, not an expected period difference.",
            "diagnostics.vwapExtended / vwapDistanceAtr (crypto only)": "Crypto late-trend extension flag: when vwapExtended is true or vwapDistanceAtr is large the entry is extended. Null for non-crypto — use EMA distance + RSI/ADX there instead.",
            "atrDiagnostics.atr_value / atr_tf / atr_source": "Authoritative ATR provenance for the reviewed levels. Confirm SL is structurally valid relative to this exact ATR series; do not assume H4 or D1.",
            "diagnostics.rr / sl / tp / entry": "Risk geometry; reject when RR is unacceptable after confirmation requirements.",
            "riskGeometry.maxSlFraction / slDistanceFraction / maxSlPassed / rrRequired / rrPassed": "Server-resolved execution risk gates. Fractions use 0.025=2.5%. False maxSlPassed or rrPassed blocks ENTRY_NOW; do not invent another cap or floor.",
            "conviction / timeframeBias / regimeTf / biasTf / structureTf": "Directional alignment across the resolved policy trend roles; conflicting roles lower tradeability and can justify WAIT.",
            "engineBContext (bosConfirmed, chochConfirmed, liquiditySweep, nearestSupport/Resistance, breakerLevel, structuralVerdict, obAtZone, fvgOverlap)": "Optional structure overlay for location and entry-model selection when available=true; confirmed BOS/CHoCH with acceptance supports continuation, not chasing.",
            "nonVisualContext / intermarket / newsSentiment": "Explains why Engine A scored the setup. Advisory, non-visual — never reject only because a non-visual driver is not visible on the chart.",
        },
        "strategyMapping": {
            "CONFLUENCE_CONTINUATION": "Trending regime (ADX up) with factorScores.trend and momentum aligned and BOS confirmed in direction; enter on continuation, not after exhaustion.",
            "PULLBACK_TO_STRUCTURE": "Price pulling back toward nearestSupport/Resistance, value, or VWAP in trend direction — preferred timing, not late.",
            "BREAKOUT_RETEST": "Break of structure then retest/acceptance of breakerLevel or zone before continuation.",
            "MEAN_REVERSION_AT_VALUE": "Ranging/balancing regime (low ADX) with RSI extreme at a value edge; counter-trend only with clear rejection.",
            "NO_TRADE": "Conflicted factors, missing required context, or hard invalidation.",
        },
        "chartReadingProtocol": {
            "purpose": "How to read the chart image itself (bases, breakouts, candles, volume) before judging Engine A direction and timing. Advisory chart craft distilled from proven breakout/swing traders (Minervini VCP, O'Neil cup-and-handle, Darvas box, Qullamaggie continuation, Wyckoff/price-action candles). Never overrides deterministic scores or gates.",
            "baseQuality": [
                "A tradable continuation base shows contraction: successive pullbacks get shallower and candles overlap less (volatility contraction). Wide, loose, erratic bases after an advance read as distribution, not a coiled spring.",
                "Volume should dry up into the final contraction and expand on the breakout leg. Rising volume on down-legs inside the base is a warning. For forex/tick or mixed volume, do not score volume — use range contraction only.",
                "Best continuation candidates sit near highs in an established uptrend (higher highs/higher lows above rising EMAs); breakouts from deep, extended, or basing-after-collapse structures are lower quality.",
            ],
            "breakoutValidity": [
                "A breakout is valid only on a confirmed body close beyond the level — wicks/shadows through a level are probes, not breaks.",
                "Valid breakouts show volume expansion (roughly 1.4-1.5x average or more on real-volume assets) and follow-through; a breakout that closes back inside the prior range within 1-2 bars is a FAILED breakout — downgrade and consider the opposite read.",
                "Retest/acceptance entries (price breaks, pulls back to the broken level, holds, resumes) are preferred timing over chasing the impulse candle.",
                "Measure extension in ATR units (atrDiagnostics.atr_tf): entry far beyond the pivot with no retest AND degraded RR is late — WAIT, not ENTRY_NOW.",
            ],
            "candleConfirmation": [
                "At pullback/structure levels look for rejection candles: bullish/bearish engulfing, pin bar (hammer/shooting star) with wick >= 2x body, or an inside-bar break in the trade direction — followed by a close in the direction of the trade.",
                "A single candle pattern in mid-range with no level, no trend context, and no follow-through is noise, not confirmation.",
                "Confirmed bars only: the rightmost forming candle is not proof of a close, breakout, or rejection.",
                "Exhaustion read: after a long directional run, climactic wide-range candles into a level with wick rejection argue for WAIT, not continuation entry.",
            ],
            "targetContext": [
                "Classical measured-move context: pattern depth projected from the breakout point gives a sanity check on whether server TP1/TP2 are realistic relative to structure; never recompute or replace server levels.",
                "Prefer entries where the opposing structure/zone leaves room to TP1 before the next major level.",
            ],
        },
        "invalidations": [
            "Identify what would invalidate the directional thesis.",
            "Check whether SL is structurally valid relative to ATR and structure.",
            "Reject when RR is unacceptable after confirmation requirements.",
            "A confirmed close back inside the broken level against the trade direction invalidates a breakout/continuation read.",
        ],
        "mustRejectIf": [
            "Direction valid but entry is measurably extended (far from value/structure with no pullback AND RR degraded), exhausted, or chasing — not merely continuing after a confirmed BOS with acceptance.",
            "Score high but location is poor for the proposed direction.",
            "Factor alignment is conflicted or weak across trend/momentum/volume.",
            "Required context is missing and blocks confident tradeability.",
            "Visual chart contradicts Engine A direction or entry timing.",
        ],
        "requiredOutputFields": [
            "tradeSkillVersion",
            "reviewType",
            "decision",
            "direction",
            "confidence",
            "entryAllowedNow",
            "waitReason",
            "noTradeReason",
            "chartReadSummary",
        ],
    }
